import pymysql

conn = pymysql.connect(host="localhost",user="root",passwd="",db="eventmanagement")
mycurousr = conn.cursor()

mycurousr.execute("""CREATE TABLE USER(
USER_ID VARCHAR(5) PRIMARY KEY NOT NULL,
USER_PASSWORD VARCHAR(30),
USER_NAME VARCHAR(30),
USER_EMAIL VARCHAR(30),
PHONENUM VARCHAR(12),
USER_TYPE VARCHAR(1)
)
""")

mycurousr.execute("""CREATE TABLE ADMIN(
USER_ID VARCHAR(5) PRIMARY KEY NOT NULL,
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
)
""")

mycurousr.execute("""CREATE TABLE STUDENT(
USER_ID VARCHAR(5) PRIMARY KEY NOT NULL,
STUDENT_GENDER VARCHAR(1),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
)
""")

mycurousr.execute("""CREATE TABLE TEACHER(
USER_ID VARCHAR(5) PRIMARY KEY NOT NULL,
TEACHER_AGE SMALLINT,
TEACHER_GENDER CHAR(1),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
)
""")

mycurousr.execute("""CREATE TABLE PARENT(
PARENT_ID VARCHAR(5) PRIMARY KEY NOT NULL,
USER_ID VARCHAR(5),
PARENT_NAME VARCHAR(10),
PARENT_AGE SMALLINT,
PARENT_GENDER CHAR(1),
PARENT_PHONENUM VARCHAR(12),
RELATIONSHIP VARCHAR(20),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
)
""")

mycurousr.execute("""CREATE TABLE EVENT(
EVENT_ID VARCHAR(5) PRIMARY KEY NOT NULL,
EVENT_NAME VARCHAR(30),
EVENT_TYPE VARCHAR(30),
EVENT_DESCRIPTION VARCHAR(2000),
EVENT_START_DATE DATE,
EVENT_END_DATE DATE,
EVENT_VENUE VARCHAR(30),
EVENT_TICKET_PRICE INT,
EVENT_TICKET_LEFT INT,
NOOFPARTICIPANT INT,
REGISTRATIONDEADLINE DATE,
USER_ID VARCHAR(5),
FOREIGN KEY (USER_ID) REFERENCES ADMIN(USER_ID)
)
""")

mycurousr.execute("""CREATE TABLE EVENT_TEACHER(
ET_ID VARCHAR(5) PRIMARY KEY NOT NULL,
USER_ID VARCHAR(5),
EVENT_ID VARCHAR(5),
POSITION VARCHAR(20),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
)
""")

mycurousr.execute("""CREATE TABLE EVENT_STUDENT(
ES_ID VARCHAR(5) PRIMARY KEY NOT NULL,
USER_ID VARCHAR(5),
EVENT_ID VARCHAR(5),
PARENT_ID VARCHAR(5),
STATUS VARCHAR(1),
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
FOREIGN KEY (PARENT_ID) REFERENCES PARENT(PARENT_ID)
)
""")

mycurousr.execute("""CREATE TABLE RESOURCE(
RESOURCE_ID VARCHAR(5) PRIMARY KEY NOT NULL,
EVENT_ID VARCHAR(5),
RESOURCE_TYPE VARCHAR(20),
FILEDESTINATION VARCHAR(30),
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
)
""")

mycurousr.execute("""CREATE TABLE FEEDBACK(
FEEDBACK_ID VARCHAR(5) PRIMARY KEY NOT NULL,
USER_ID VARCHAR(5),
EVENT_ID VARCHAR(5),
COMMENT VARCHAR(2000),
FOREIGN KEY (USER_ID) REFERENCES STUDENT(USER_ID),
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
)
""")

mycurousr.execute("""CREATE TABLE NOTIFICATION(
NOTIFICATION_ID VARCHAR(5) PRIMARY KEY NOT NULL,
EVENT_ID VARCHAR(5),
EVENT_DATE DATE,
MESSAGE VARCHAR(2000),
FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID)
)
""")

mycurousr.execute("INSERT INTO USER(USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,PHONENUM,USER_TYPE) VALUES ('S1','ABC123123','IVAN','IVAN@GMAIL.COM','0121231233','S');")
mycurousr.execute("INSERT INTO USER(USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,PHONENUM,USER_TYPE) VALUES ('T1','ABC123123','MS TAN','BEN@GMAIL.COM','012222222','T');")
mycurousr.execute("INSERT INTO USER(USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,PHONENUM,USER_TYPE) VALUES ('T2','ABC123123','MR LOW','LOW@GMAIL.COM','012222222','T');")
mycurousr.execute("INSERT INTO USER(USER_ID,USER_PASSWORD,USER_NAME,USER_EMAIL,PHONENUM,USER_TYPE) VALUES ('A1','ABC123123','MR SENG','SENG@GMAIL.COM','0123333','A');")
mycurousr.execute("INSERT INTO STUDENT(USER_ID,STUDENT_GENDER) VALUES ('S1','M');")
mycurousr.execute("INSERT INTO ADMIN(USER_ID) VALUES ('A1');")
mycurousr.execute("INSERT INTO TEACHER(USER_ID,TEACHER_AGE,TEACHER_GENDER) VALUES ('T1',30,'F');")
mycurousr.execute("INSERT INTO TEACHER(USER_ID,TEACHER_AGE,TEACHER_GENDER) VALUES ('T2',35,'M');")
mycurousr.execute("INSERT INTO PARENT(PARENT_ID,USER_ID,PARENT_NAME,PARENT_AGE,PARENT_GENDER,PARENT_PHONENUM,RELATIONSHIP) VALUES ('P1','S1','BOO',30,'M','01244232323','FATHER');")
mycurousr.execute("INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DESCRIPTION,EVENT_START_DATE,EVENT_END_DATE,EVENT_VENUE,EVENT_TICKET_PRICE,EVENT_TICKET_LEFT,NOOFPARTICIPANT,REGISTRATIONDEADLINE,USER_ID) VALUES ('E1','RUN','MARATHON','10KM AND 5KM MARATHON','2019-9-5','2019-9-5','MMU',20,500,1,'2019-8-20','A1');")
mycurousr.execute("INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DESCRIPTION,EVENT_START_DATE,EVENT_END_DATE,EVENT_VENUE,EVENT_TICKET_PRICE,EVENT_TICKET_LEFT,NOOFPARTICIPANT,REGISTRATIONDEADLINE,USER_ID) VALUES ('E2','SWIM','MARATHON','5KM COMPETITION','2019-10-5','2019-10-5','MMU',20,500,0,'2019-9-28','A1');")
mycurousr.execute("INSERT INTO EVENT(EVENT_ID,EVENT_NAME,EVENT_TYPE,EVENT_DESCRIPTION,EVENT_START_DATE,EVENT_END_DATE,EVENT_VENUE,EVENT_TICKET_PRICE,EVENT_TICKET_LEFT,NOOFPARTICIPANT,REGISTRATIONDEADLINE,USER_ID) VALUES ('E3','FESTIVAL','FESTIVAL','MALAYSIA FESTIVAL','2019-10-20','2019-10-20','MMU',20,500,0,'2019-9-28','A1');")
mycurousr.execute("INSERT INTO EVENT_STUDENT(ES_ID,USER_ID,EVENT_ID,PARENT_ID,STATUS) VALUES('ES1','S1','E1','P1','Y');")
mycurousr.execute("INSERT INTO EVENT_TEACHER(ET_ID,USER_ID,EVENT_ID,POSITION) VALUES('ET1','T1','E1','LEADER');")
mycurousr.execute("INSERT INTO EVENT_TEACHER(ET_ID,USER_ID,EVENT_ID,POSITION) VALUES('ET2','T2','E1','CO-LEADER');")
mycurousr.execute("INSERT INTO FEEDBACK(FEEDBACK_ID,USER_ID,EVENT_ID,COMMENT) VALUES('FB1','S1','E1','GOOD EVENT')")

conn.commit()
conn.close()